### ISSUE TITLE
How to do individual column Searching?

### ISSUE THREAD

**Issue by Zapnologica** [ALMMa/datatables.mvc#14]
I am trying to get individual column searching working.

I have implemented the server side and works perfectly with the global search. Order etc.

I have added the search bars to the table footer as so:

```
        // Apply the search
        exRowTable.columns().eq(0).each(function (colIdx) {
            $('input', exRowTable.column(colIdx).footer()).on('keyup change', function () {
                exRowTable
                    .column(colIdx)
                    .search(this.value)
                    .draw();
            });
        });
```

However when I break on my server side controller.     public async Task<ActionResult> AjaxHandler([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest param)

All the coloumns search values are "" ?

What am I missing here?

**Comment by kjkrum** [comment]
@Zapnologica What was your solution?
