### ISSUE TITLE
Setting "searching" to false in Javascript throws exception

### ISSUE THREAD

**Issue by maximejobin** [ALMMa/datatables.mvc#16]
When setting the "searching" option to "false", an exception is thrown because the search value provided is null.

Example:
```
$('#datas').dataTable({
	"searching": false
});
```

Removing the "if" validation solves the problem.

It should be the developer's responsibility to check if the search value is null or has a value.

**Comment by levipage** [comment]
I get this same error even when I have search enabled. 
        <title>The value of the search cannot be null. If there's no search performed, provide an empty string.<br>Parameter name: value</title>

**Comment by maximejobin** [comment]
You can see I provided a pull request that I applied to my fork.  There is only one line to comment.

See the project here: https://github.com/maximejobin/datatables.mvc

**Comment by levipage** [comment]
Thanks, yeh I ended up looking at what you did and fixed it as you described.
